[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    tzapu/WiFiManager
    olikraus/U8g2
    mathertel/RotaryEncoder
    madhephaestus/ESP32Servo